### ISSUE TITLE
Type error in Craft 4 in 5.0.2

### ISSUE THREAD

**Issue by maccadesign** [FosterCommerce/klaviyoconnect#102]
Hi, there's a type error on v5.0.2 in the ApiController on Craft 4:

` Type of fostercommerce\\klaviyoconnect\\controllers\\ApiController::$allowAnonymous must be array|int|bool (as in class craft\\web\\Controller) at /home/forge/rhinostationery.com/vendor/fostercommerce/klaviyoconnect/src/controllers/ApiController.php:16)"`

Many thanks
Andrew

**Comment by fantasticmachine** [comment]
@maccadesign Apologies for the slow response. Thanks for letting us know about this. We'll get a fix rolled out asap.

**Comment by fantasticmachine** [comment]
@maccadesign New version, 5.0.4, released which should fix this problem.
