### ISSUE TITLE
Fresh Install profileMappings error

### ISSUE THREAD

**Issue by IndigoViking** [FosterCommerce/klaviyoconnect#11]
Fresh install of Craft 3 and Klaviyo Connect. When trying to visit the settings page for this plugin I get this error.

`Neither the property "profileMappings" nor one of the methods "profileMappings()", "getprofileMappings()"/"isprofileMappings()"/"hasprofileMappings()" or "__call()" exist and have public access in class "fostercommerce\klaviyoconnect\variables\Variable".`

**Comment by johnnynotsolucky** [comment]
Thank you @IndigoViking, this is resolved in v3.0.1
