### ISSUE TITLE
Use Variant image vs Product Image?

### ISSUE THREAD

**Issue by MaddieB-MWCompany** [FosterCommerce/klaviyoconnect#112]
How can I use a variant image as the "product image handle" vs the product image?

**Comment by fantasticmachine** [comment]
Hi there. Can you help me understand a little better what it is you are trying to achieve?
If I understand correctly, could you add another image field to the Product, place your Variant Image in there and pass the handle for that field to Klaviyo?

**Comment by peteeveleigh** [comment]
Closing due to no further information from OP
