### ISSUE TITLE
event and $event and special properties

### ISSUE THREAD

**Issue by davecosec** [FosterCommerce/klaviyoconnect#12]
is there a built in method to send $event_id instead of event_id and $value instead of value when it comes to sending data to Klaviyo ?

These are special properties in Klaviyo

**Comment by johnnynotsolucky** [comment]
Hi @davecosec, those properties are mapped to the format expected by Klaviyo: https://github.com/FosterCommerce/klaviyoconnect/blob/master/src/models/Base.php#L47. They're just passed in sans the $.

**Comment by davecosec** [comment]
ah, I've updated to 3.0.6 thanks!
