### ISSUE TITLE
Klaviyo API Changes June 2024

### ISSUE THREAD

**Issue by mcjackson18** [FosterCommerce/klaviyoconnect#123]
Hi, I wanted to check if this plugin be compatible with latest [Klaviyo API changes](https://developers.klaviyo.com/en/docs/migrating_from_v1v2_to_the_new_klaviyo_apis), the current v1/v2 APIs are set to be retired on 30th June 2024, thanks.

**Comment by iamkeir** [comment]
+1

**Comment by mdarrik** [comment]
Yep. We're planning out the work now.

**Comment by mcjackson18** [comment]
Great, thanks for the update @mdarrik.

**Comment by cbovers** [comment]
+1

**Comment by johnnynotsolucky** [comment]
https://github.com/FosterCommerce/klaviyoconnect/releases/tag/6.0.0-beta.1 is released which includes changes to use the newest Klaviyo API.

A few of the changes are breaking changes - They were necessary to more closely align the plugins functionality with Klaviyo's API.

Give it a whirl!

**Comment by cbovers** [comment]
Hello, is there any chance you could also release the changes for a version compatible with craft cms 3?
Kind regards

**Comment by iamkeir** [comment]
+1 for Craft 3. We're not quite ready to upgrade our Craft 3 site.

**Comment by steve-moresoda** [comment]
Another +1 for Craft 3. Unlikely to be upgrading one of our sites in the near future.

**Comment by alangrahambs** [comment]
We are also working with a fair few Craft v3 sites and would dearly love for the plugin to be v3 compatible.

**Comment by shetlandrew** [comment]
+1 from me too. We desperately need this work with Craft 3. It would take a very long time to upgrade our sites to Craft 4 and need them to work with Klaviyo.

**Comment by daniellelecomte** [comment]
+1

**Comment by johnnynotsolucky** [comment]
We're working on updating the Craft 3 version in the next week. I'll update as soon as we have  a version ready.

**Comment by johnnynotsolucky** [comment]
https://github.com/FosterCommerce/klaviyoconnect/releases/tag/4.2.0-beta.1 is released which supports Craft 3 and uses the new Klaviyo API. Please give it a go and report any issues you might have, and I'll look into them ASAP.

**Comment by iamkeir** [comment]
Thank you **so much** guys 🙏

**Comment by alangrahambs** [comment]
Thank you, thank you, thank you.  We can't wait to give this a go!

**Comment by mcjackson18** [comment]
Thanks guys for both the Craft 3 and Craft 4 updates 👍🏻

**Comment by laneigemud1990** [comment]
> https://github.com/FosterCommerce/klaviyoconnect/releases/tag/4.2.0-beta.1 is released which supports Craft 3 and uses the new Klaviyo API. Please give it a go and report any issues you might have, and I'll look into them ASAP.
> 
> As before, please review the [changelog](https://github.com/FosterCommerce/klaviyoconnect/blob/4.2.0-beta.1/CHANGELOG.md) for breaking changes.

Hi there,

I'm getting an error with this Craft 3 beta version. To replicate, I'm just attempting to change the status of an order. 
Craft CMS 3.7.66
PHP: 7.4.33

`Argument 3 passed to fostercommerce\klaviyoconnect\services\Track::createProfile() must be an instance of fostercommerce\klaviyoconnect\services\mixed or null, array given, called in /var/www/html/deploy/vendor/fostercommerce/klaviyoconnect/src/services/Track.php on line 249`


<br class="Apple-interchange-newline">

**Comment by johnnynotsolucky** [comment]
Thanks @laneigemud1990, this should be fixed https://github.com/FosterCommerce/klaviyoconnect/releases/tag/4.2.0-beta.2. The `mixed` type is only available from PHP 8 onwards.

**Comment by laneigemud1990** [comment]
> Thanks @laneigemud1990, this should be fixed https://github.com/FosterCommerce/klaviyoconnect/releases/tag/4.2.0-beta.2. The `mixed` type is only available from PHP 8 onwards.

Thanks for jumping on it so quickly! That seems to have done the trick.

**Comment by samuelbirch** [comment]
Hey @johnnynotsolucky, any eta on a craft 5 version?

**Comment by johnnynotsolucky** [comment]
@samuelbirch I've created a separate tracking issue to handle the upgrade for Craft 5 compat: https://github.com/FosterCommerce/klaviyoconnect/issues/127

**Comment by matt-adigital** [comment]
Hey, I can see craft 3 and craft 5 versions are in beta for this functionality, any chance of a craft 4 version? We only recently upgraded the site from craft 3 to craft 4 so there won't be much apetite from the client to go up to craft 5 anytime soon. Will craft 4 be supported or abandoned? Thanks.

**Comment by JoeriE** [comment]
With the new beta (6.0.0.beta1) I get an error If i want to add a custom event and adding this line to the form:
`<input type="hidden" name="event[name]" value="Started Checkout" />`

The error:
```[400] Client error: `POST https://a.klaviyo.com/api/events/` resulted in a `400 Bad Request` response:\n{\"errors\":[{\"id\":\"aacaf2b2-0097-4b16-9fc8-388d0db1aa42\",\"status\":400,\"code\":\"invalid\",\"title\":\"Invalid input.\",\"detail\": (truncated...)\n```

**Comment by johnnynotsolucky** [comment]
@JoeriE I've tested with the following:

```twig
<form method="POST">
  {{ csrfInput() }}
  <input type="hidden" name="action" value="/klaviyoconnect/api/track" />
  <!-- Event to track -->
  <input type="hidden" name="event[name]" value="My Custom Event" />
  <!-- Profile Details -->
  <label>
    Email
    <input type="email" name="email" />
  </label>
  <input type="submit" value="Submit" />
</form>
```

And with some more data:

```twig
<form method="POST">
  {{ csrfInput() }}
  <input type="hidden" name="action" value="/klaviyoconnect/api/track" />
  <!-- Event to track -->
  <input type="hidden" name="event[name]" value="Event Foo" />
  <input type="hidden" name="event[unique_id]" value="a1b2c3" />
  <input type="hidden" name="event[value]" value="100.98" />
  <input type="hidden" name="event[value_currency]" value="USD" />
  <input type="hidden" name="event[FooBar]" value="Foo Bar" />
  <!-- Profile Details -->
  <label>
    Email
    <input type="email" name="email" />
  </label>
  <input type="submit" value="Submit" />
</form>
```

The events are tracked correctly in Klaviyo:

![image](https://github.com/FosterCommerce/klaviyoconnect/assets/4161106/0126eb1f-805f-4ddb-bd66-f9097b1f1c35)

I _am_ able to replicate the error message by submitting a form with an invalid email address. For example using `"my-email"` will result in:

```
[400] Client error: `POST https://a.klaviyo.com/api/events/` resulted in a `400 Bad Request` response:
{"errors":[{"id":"5ada7c38-4b8b-4736-87ff-433efb4ce52d","status":400,"code":"invalid","title":"Invalid input.","detail": (truncated...)
```

Could you share the full html of the form that's being submitted (excluding any secrets)?

**Comment by johnnynotsolucky** [comment]
@JoeriE I think that the issue you're having is with the `profile[language]` input field. With the new API, all custom properties that you want to attach to a profile need to go into a `"properties"` field: https://developers.klaviyo.com/en/reference/create_profile

You should be able to change that field to

```twig
<input type="hidden" name="profile[properties][language]" value="{{ craft.app.locale.id }}" />
```

I see I missed a section in the docs for this, I'll get that updated. But you can refer to the [examples](https://klaviyoconnect.fostercommerce.com/Templating.html#extra-profile-properties) which have been correctly updated.

**Comment by sjcallender** [comment]
🎉 Craft 5 and Commerce 5 support has been added in https://github.com/FosterCommerce/klaviyoconnect/releases/tag/7.0.0
