### ISSUE TITLE
Craft 5 Compatibility

### ISSUE THREAD

**Issue by johnnynotsolucky** [FosterCommerce/klaviyoconnect#127]
Tracking issue for Craft 5 compatibility upgrade over the next few months.

**Comment by aarmitage** [comment]
Any news on an eta for a Craft 5 release?

**Comment by johnnynotsolucky** [comment]
Tracking branch for Craft 5 compatibility: https://github.com/FosterCommerce/klaviyoconnect/tree/craft-5

Please note that these are initial changes, and that they haven't been tested yet.

**Comment by johnnynotsolucky** [comment]
🎉 Craft 5 and Commerce 5 support has been added in https://github.com/FosterCommerce/klaviyoconnect/releases/tag/7.0.0
