### ISSUE TITLE
Settings Page Error

### ISSUE THREAD

**Issue by mcjackson18** [FosterCommerce/klaviyoconnect#15]
Version: 3.1.0

The plugin settings page (/admin/settings/plugins/klaviyoconnect) gives an `Undefined property: stdClass::$status` error. The error is in /vendor/fostercommerce/klaviyoconnect/src/variables/Variable.php at line 22.

This is a fresh install and the first time the settings page has been accessed.

**Comment by johnnynotsolucky** [comment]
Thank you @mcjackson18. This is resolved in 3.1.1.
