### ISSUE TITLE
Product catalog feeds

### ISSUE THREAD

**Issue by sjcallender** [FosterCommerce/klaviyoconnect#2]
Create feed URL for Klaviyo to use to populate product catalog in Klaviyo

**Comment by johnnynotsolucky** [comment]
@sjcallender I think the plugin used to manage products would be best to generate a product feed. Have a look at this example of a blog feed from Craft: https://docs.craftcms.com/v2/templating/rss-feed.html

We can add a template which generates a feed of all products for us in Craft without worrying about updating the plugin.

It would also be difficult to figure out how to generate the feed from the plugin alone. Sites which use services like Recurly for example, we'll be adding a lot of extra work to get that feed into Klaviyo.

**Comment by RitterKnightCreative** [comment]
Have you guys found the json format used for catalog feeds? Found the web feeds in their docs but the product feeds says to contact support.

**Comment by johnnynotsolucky** [comment]
@RitterKnightCreative there's some useful info here if you haven't seen it already: https://help.klaviyo.com/hc/en-us/articles/115005258768-Add-a-Custom-Web-Feed-to-a-Campaign#adding-a-custom-web-feed1

They also have an example feed in JSON format: https://klaviyo.zendesk.com/api/v2/help_center/en-us/articles.json

**Comment by RitterKnightCreative** [comment]
Got a chance to connect with Klaviyo support on this. 

There's a few things on their end that need to get setup but the feed itself is pretty straightforward to implement. There's a hidden page or two that's not usually accessed for a custom store... Shopify and BigCommerce expose the page through their API apparently but support needs to get it setup before custom integrations use it. Fun.

They sent me these [docs](https://help.klaviyo.com/attachments/token/mZ2rjQfoEcLjs5OMrXyIeOiK3/?name=Klaviyo+Custom+Catalog.zip).

**Comment by sjcallender** [comment]
@RitterKnightCreative Are you able to access [https://www.klaviyo.com/catalog/sources](https://www.klaviyo.com/catalog/sources)?

**Comment by RitterKnightCreative** [comment]
@sjcallender yes.

**Comment by sjcallender** [comment]
We are not implementing a more advanced feature. Documentation on how to add a product feed has been added here: https://klaviyoconnect.fostercommerce.com/feed.html
