### ISSUE TITLE
Syncing Historical Data

### ISSUE THREAD

**Issue by williamhibberd** [FosterCommerce/klaviyoconnect#25]
Is there a way to [Syncing Historical Data](https://help.klaviyo.com/hc/en-us/articles/115005082927-Integrate-a-Standard-Ecommerce-Platform#syncing-historical-data11) with Klaviyo through this plugin? It would be great to be able to send all placed orders to the Klaviyo prior to installing the plugin.

Thanks for the great work

**Comment by sjcallender** [comment]
This is now a part of the plugin as of version 4.0. You'll find it at Utilities > Klaviyo Connect.
