### ISSUE TITLE
Klaviyo Events not tracking properly

### ISSUE THREAD

**Issue by michaelramuta** [FosterCommerce/klaviyoconnect#26]
I'm having a few issues with events:
- When adding items to cart, the Updated Cart event will set value, price, and qty to 0 and items will be empty
- Ordered Product and Placed Order events often are not firing at all

**Comment by sjcallender** [comment]
@michaelramuta - Hopefully the new version ([4.0.0](https://github.com/FosterCommerce/klaviyoconnect/releases/tag/4.0.0)) will resolve those issues for you.
