### ISSUE TITLE
Send Commerce coupon codes to Klaviyo

### ISSUE THREAD

**Issue by sjcallender** [FosterCommerce/klaviyoconnect#3]
Create coupon in Craft that can be dynamically added to Klaviyo for insertion into auto-generated email.

**Comment by johnnynotsolucky** [comment]
@sjcallender I think the same applies as with #2; Commerce lets you define a bunch of coupons and expiry etc, we just need to write a plugin to export them. 

We could add a hook to KlaviyoConnect for user-defined coupon exporting so we're not tying into a specific plugin like Commerce?

**Comment by johnnynotsolucky** [comment]
Having a look at this post: https://www.klaviyo.com/blog/feature-spotlight-generating-unique-one-time-coupon-codes-for-shopify-plus

It would be cool to build an integration with Klaviyo, I'd think it would be a Craft Commerce integration though, depending on what the requirements are.
