### ISSUE TITLE
Ability to use the subscribe endpoint when adding users to a Klaviyo list via twig

### ISSUE THREAD

**Issue by pepsDev** [FosterCommerce/klaviyoconnect#42]
If users are added to a list via a Twig template, they currently skip the klaviyo double opt-in process.
Would it be possible to specify in the template whether the member endpoint or [subscription endpoint](https://www.klaviyo.com/docs/api/v2/lists#post-subscribe) is used?

See [Klaviyo API Docs](https://www.klaviyo.com/docs/api/v2/lists#post-subscribe):
>  If you would like to subscribe profiles to a list and use the double opt-in settings for the list please use the subscribe endpoint.

**Comment by benface** [comment]
Added in [v4.0.5](https://github.com/FosterCommerce/klaviyoconnect/releases/tag/4.0.5). Thank you for requesting this!
