### ISSUE TITLE
Not checking for billing address before grabbing the firstName and lastName.

### ISSUE THREAD

**Issue by simeon-smith** [FosterCommerce/klaviyoconnect#43]
When you are tracking an order you are not checking if the billing address exists before accessing the firstName and lastName which causes it to fail and to fail any attempted craft action on the cart.

**Comment by deviarte** [comment]
Yeah, this breaks cart updates pretty much right on install.

Trying to get property 'firstName' of non-object

https://github.com/FosterCommerce/klaviyoconnect/blob/master/src/services/Track.php#L135

**Comment by williamhibberd** [comment]
This is also a breaking update on a couple of sites I have klaviyoconnect installed on. We have rolled back to 4.0.2 for the mean time. Will @sjelfull's commit be merged in 4.0.3?

**Comment by johnnynotsolucky** [comment]
@sjelfull's patch has been published in 4.0.4
