### ISSUE TITLE
Support for Guzzle 7

### ISSUE THREAD

**Issue by pepsDev** [FosterCommerce/klaviyoconnect#51]
I'm using Klaviyoconnect with the Commerce [Mollie Plugin](https://github.com/craftcms/commerce-mollie).
The Mollie-Plugin now requires Guzzle 7. When I want to update the plugin Mollie Plugin to 3.0 klavioconnect is locked to an lower guzzle version.

    - fostercommerce/klaviyoconnect is locked to version 4.0.4 and an update of this package was not requested.
    - Conclusion: don't install guzzlehttp/guzzle 7.3.0 (conflict analysis result)

**Comment by jripmeester** [comment]
Running into the same problem on a new project. Hope the Guzzle version can be bumped.

**Comment by sjcallender** [comment]
Okay. Thanks for reporting. We'll take a look next week.

**Comment by johnnynotsolucky** [comment]
@pepsDev @jripmeester this is resolved in v4.0.6.
