### ISSUE TITLE
Perfect for recovering abandoned carts...

### ISSUE THREAD

**Issue by smockensturm** [FosterCommerce/klaviyoconnect#63]
How? How can I do this with this plugin?

What does this mean: _"Before you can use this flow, you must start syncing **Started Checkout** events whenever a shopper begins the checkout process."_

https://help.klaviyo.com/hc/en-us/articles/115005082927-Integrate-a-Custom-Ecommerce-Cart-or-Platform#started-checkout5

![preview-lightbox-image](https://user-images.githubusercontent.com/6586518/126395835-5408068f-3cea-40f6-bead-9ffdef03c894.png)

**Comment by sjcallender** [comment]
Hi @smockensturm,
You'll want to add custom event to your templates. If you're using Twig, then our documentation shows how to do that here. https://klaviyoconnect.fostercommerce.com/Templating.html#track-event

```
<form method="POST">
    <input type="hidden" name="action" value="/klaviyoconnect/api/track" />
    <!-- Event to track -->
    <input type="hidden" name="event[name]" value="Started Checkout" />
    <!-- Profile Details -->
    <label>
      Email
      <input type="email" name="email" />
    </label>
    <input type="submit" value="Submit" />
</form>
```


Here's another example for a live site we maintain.
```
<form method="post">
  
  {{ csrfInput() }}
  {{ actionInput('klaviyoconnect/api/track') }}
  <input type="hidden" name="forward" value="/commerce/cart/update-cart">
  {{ redirectInput('store/checkout/addresses') }}
  <input type="hidden" name="event[name]" value="Started Checkout" />
....
<form>
```

Give it a whirl.

p.s. - If you're looking for help within the Klaviyo interface, we're happy to offer consultation, but Klaviyo will probably help for free. ;)

**Comment by smockensturm** [comment]
hello @sjcallender  oh man just what i needed. of course. great work, thank you for the response.

**Comment by sjcallender** [comment]
Happy to help!
