### ISSUE TITLE
Klaviyo Events

### ISSUE THREAD

**Issue by RitterKnightCreative** [FosterCommerce/klaviyoconnect#7]
Suggest changing the ``Completed Order`` event to the more standard ``Placed Order`` and follow their JSON.

For example, in the default flow library, Klaviyo is expecting the ``Placed Order`` event:

![screen shot 2018-10-29 at 4 44 43 pm](https://user-images.githubusercontent.com/3707869/47682321-06c7bd00-db9a-11e8-9878-a749da56e2b1.png)

Also, Klaviyo [suggests sending the Order Items](https://help.klaviyo.com/hc/en-us/articles/115005082927-Integrate-a-Custom-Ecommerce-Cart-or-Platform#orders-and-order-items5) as well. 

Seems like that's within the wheelhouse of this?

**Comment by johnnynotsolucky** [comment]
Awesome @RitterKnightCreative! Thanks for finding these docs. I'll update the events to use these new naming conventions instead.

**Comment by engram-design** [comment]
+1 for this, particularly the new naming conventions. We're just working on this with a client migrating from Magento, and are looking to have these sort of events hooked up.

For instance, the "Updated Cart" content is getting into Klaviyo, but its not formatted in a few user-friendly way like the Magento plugin does. I'm not sure if this is just because Magento is a bit special as officially supported, but according to the docs, the data being sent is structured differently.

I also might look at putting together a PR to open up the `trackOrder()` function (which is currently private), so that we can setup our own hooks to utilise this (to replicate https://help.klaviyo.com/hc/en-us/articles/115005254528-Review-and-Understand-your-Magento-Data)

**Comment by johnnynotsolucky** [comment]
@engram-design PRs are always welcome 🙂

WRT to the naming conventions, this is long overdue. I'll get on those as soon as I get a chance.

**Comment by RitterKnightCreative** [comment]
@engram-design I pinged Klaviyo awhile back on this and apparently the dashboard formatting is a known issue when using the custom API.  

> Unfortunately, this is a known UI issue with custom events that we do not have a fix for at this time. But as far as pulling in any event data into your email template goes, you shouldn't run into any issues in that regard.

It definitely feels like if you're not using Shopify, Woo, Magento or BigCommerce, you're going against the grain. Maybe if enough of us complain, they'll get the UI sorted. 

You might be onto something with data formatting. We're sending the [Started Checkout](https://help.klaviyo.com/hc/en-us/articles/115005082927-Integrate-a-Custom-Ecommerce-Cart-or-Platform#checkout-started4) event per JS (and not via the plugin) and Klaviyo is still formatting it funky. I have no idea why their docs refer to it as "Checkout Started" but their code examples are correct and mention Started Checkout.

Would be interesting to dig into Magento's code and see what it's doing differently.... is it server side vs JS, what parameters, etc.

**Comment by engram-design** [comment]
@RitterKnightCreative More than happy to throw you the Magento plugin for reverse-engineering (what I'm doing), and I believe they use both JS and PHP methods, as the docs themselves recommend. Feel free to ping me on the Craft Slack (crawf)

Also got in touch with Klaviyo, and they said the nice UI in metrics is only for officially supported connectors, like Magento, so that's just how it has to be sadly. Got the same response you've stated.

So yeah, It looks as though this plugin's events are covering the server-side items (Orders and Order Items), and the rest should be custom JS.

**Comment by sjcallender** [comment]
> Might also be worth getting Brandon or other P&T brass on the horn with a product manager at Klaviyo to get Commerce as an "official" install. From a client perspective, it certainly looks like something is off even if emaills are working properly.

@RitterKnightCreative I'll do that.

**Comment by sjcallender** [comment]
I've resumed my conversation with Klaviyo about an official integration. I'll keep you all updated on how that goes.

**Comment by keyurshah** [comment]
Hi @sjcallender ! any update on an official integration? Thanks!

**Comment by sjcallender** [comment]
@keyurshah We're in communication, but nothing official has been agreed or acted upon. We're scheduling a product review for more of their team members.

**Comment by johnnynotsolucky** [comment]
@RitterKnightCreative I've released v3.0.0. I've updated the data that is sent to Klaviyo to align with how they're expecting it. There's also a number of other changes to clean up the plugin API, checkout the docs here: https://klaviyoconnect.fostercommerce.com/ 🙂

**Comment by sjcallender** [comment]
Regarding an official integration with Klavyio, Klaviyo's dev team is going to create a Craft Commerce service in their API that we'll be able to use to add a Craft logo to identify Events. They're also going to give us some new docs to review for some new features about to be released. Not sure of the ETA.

**Comment by engram-design** [comment]
@johnnynotsolucky Just wanted to follow this up with 3.0 - did you implement the following events?

- Placed Order
- Ordered Product
- Fulfilled Order

It seems like `Placed Order` is still named `Placed Order`, and the other two are missing. Would you be open to a PR that renames this event, but also implements the other two?

I note there's a `Updated Cart` which I won't be using (we're doing a 1-for-1 integration with [Magento](https://help.klaviyo.com/hc/en-us/articles/115005254448-Properties-for-Synced-Magento-Orders)), but I suppose that's handy to have

@sjcallender Nice to hear about that - nothing new I imagine?

**Comment by johnnynotsolucky** [comment]
@engram-design no I didn't. I think we can use this: https://docs.craftcms.com/commerce/v2/events.html#order-related-events

Will probably need a new config item in the settings model to select which status marks an order as fulfilled. I don't think every Commerce install has the same set of order statuses.

**Comment by engram-design** [comment]
After posting this, I did wonder if its more project-specific and tied to whether or not there's a fulfilled order status, but a config settings makes perfect sense, and is simple to implement. Just need to check whether there is a value on this setting to send the event or not!

I would suggest the `orderStatusChange` event.

Thanks!

**Comment by johnnynotsolucky** [comment]
Yeah agreed. Alternatively you could implement it in a site module with something like

```php
KlaviyoConnect::getInstance()->track->trackOrder(
    'Fulfilled Order',
    $myOrder,
    new Profile([
        'id' => $user->id,
    ])
)
```

**Comment by engram-design** [comment]
Yep, that's what I'm currently doing, just pitching it whether or not to include it natively!

**Comment by RitterKnightCreative** [comment]
@sjcallender @engram-design how are you guys setting up new accounts with Klaviyo? 

Just created a new account today and all the default flows are now only available with the official integrations. 

Tried to work around this by changing the trigger using an official one and switching back. but it looks like the flow is not changeable anymore...

**Comment by RitterKnightCreative** [comment]
I think an officiall supported integration couldn't come soon enough on this...

**Comment by RitterKnightCreative** [comment]
@sjcallender Not sure if you've heard any movement on an official integration?

**Comment by sjcallender** [comment]
Hey everyone. A long-overdue update has been published. https://github.com/FosterCommerce/klaviyoconnect/releases/tag/4.0.0

@RitterKnightCreative - Unfortunately, the conversion about the official integration stalled. I've tried to revive it but have heard crickets.

> Tried to work around this by changing the trigger using an official one and switching back. but it looks like the flow is not changeable anymore...
We're seeing the same thing and helping clients copy those defaults if they need them. Kind of sucks.
