### ISSUE TITLE
"This update requires PHP ^7.2, but your environment is currently running PHP 8.0.8"

### ISSUE THREAD

**Issue by iamkeir** [FosterCommerce/klaviyoconnect#88]
We are being prompted to run an update but receiving "This update requires PHP ^7.2, but your environment is currently running PHP 8.0.8". This is curious as the previous version of the app has been running on v8 - so I'm guessing there is a misguided gremlin in the system :D

Great plugin, btw - thanks!

**Comment by fantasticmachine** [comment]
Hi @iamkeir Yeah we had a few issues last week regarding getting both a Craft 3 and a Craft 4 version available simultaneously.

I think I know what's up here. Can you confirm, as I suspect, that you are running Craft 3 on PHP 8?

**Comment by iamkeir** [comment]
@fantasticmachine thanks for fast reply! Yes, we're Craft 3 on PHP 8, specifically:
PHP 8.0.8
Craft Pro 3.7.46
Klaviyo Connect 4.0.10

And I've got two updates listed for Klaviyo Connect, 4.0.11 and 4.0.12.

I've tried your suggestion which seems to have done the trick for now. Do we need to be mindful of new versions using this method?

**Comment by fantasticmachine** [comment]
@iamkeir I had a minute before I needed to dash out, so I have published a release for 4.0.13. You can now change your composer file requirement back to "^4.0" and it should be fine.

**Comment by iamkeir** [comment]
@fantasticmachine YOU DE BEST! Thank you for sorting so quickly.
