### ISSUE TITLE
Add the "time"-property to sync of old orders

### ISSUE THREAD

**Issue by SandraSundqvist** [FosterCommerce/klaviyoconnect#91]
Hi,

When syncing old orders to Klaviyo all the "Placed order"- events/metrics (that are sent then) are registered in Klaviyo on the day of the sync, instead of on the date the orders were made.

Because of that, the data under the analytics section in Klaviyo looks a bit funky, and it's hard to do anything useful with the "Placed order"-metrics, as they are registered on the wrong date. Wouldn't it be better to add the _time_ property with the timestamp from the order when syncing old orders? Then the metrics should get registered on the correct date.

Maybe by adding the timestamp of the order to the `trackOrder` function in `queue/jobs/SyncOrders.php`:

```
public function execute($queue)
{
    $this->setProgress($queue, 1);

    if ($this->orderId) {
        $order = Order::find()->id($this->orderId)->one();

        if ($order) {
            $timeOfOrder = $order->dateOrdered !== null ? $order->dateOrdered->getTimestamp() : null;
            Plugin::getInstance()->track->trackOrder('Placed Order', $order, null, $timeOfOrder, null);
        }
    }

    return true;
}

```

Best regards,
Sandra

**Comment by fantasticmachine** [comment]
Thanks @SandraSundqvist 
We'll schedule in some time to look into this.

**Comment by johnnynotsolucky** [comment]
I have implemented this change. I think it makes sense that syncing orders from the CP will use the orders `dateOrdered` field.
